# Generated by Django 5.2.8 on 2025-11-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domino', '0005_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
